### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by kimanton** [RyanPaulMcKenna/onRobot#1]
Hello Ryan,
I tried your code for RG2 with RG6 gripper and it works! 
I would like to add the ability to monitor `rg_Busy` and `rg_Grip_detected` variables. 
However, I don't understand how the code works. Specifically, how to construct xml request (e.g. [lines 115-123](https://github.com/RyanPaulMcKenna/onRobot/blob/60fa67b7791103165681f3df87a3d98b31fd80b3/onRobot/onRobot/gripper.py#L115)) and what is going on with curl commands (e.g. [lines 130-144](https://github.com/RyanPaulMcKenna/onRobot/blob/60fa67b7791103165681f3df87a3d98b31fd80b3/onRobot/onRobot/gripper.py#L130) ).
Would you mind explaining the code if you have time?

**Comment by ViHin13** [comment]
Look at the file **/onRobot/xml_rpc_on_robot/list_methods_response.xml**.
There you find all xmlrpc commands for RG grippers.
Look at line 33 (in my file at least). Here you find the command **rg_get_busy**.
Now check the response and request variables:
1. go to  **/onRobot/xml_rpc_on_robot/**
2. open the file **xml_request_sys_method_help.xml** and change the value to **rg_get_busy**.
` <value><string>rg_get_busy</string></value>`
3. now navigate with your terminal to the folder **/onRobot/xml_rpc_on_robot/** 
4. and use this command **curl -X POST -d @xml_request_sys_method_help.xml 192.168.1.101:41414**. Change 192.168.1.101 to your robot ip
5. i dont have a rg gripper. I show you the output for the 2fg7 gripper instead:
```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param><value><array><data>                 #ignore
<value><array><data>                      #ignore
<value><string>boolean</string></value>     #This is the response type (boolean) you get back with the value
<value><string>int</string></value>        #Now follows the request part. We have to send only one variable which should be int type 
</data></array></value>                 #ignore
</data></array></value></param>           #ignore
</params>
</methodResponse>
```
6. so now you know your request and response types. In the gripper.py you can just copy the get_rg_width() function.
7. change functionname between the <methodName> tags
```
<methodCall>
    <methodName>rg_get_busy</methodName>
        <params>
            <param>
                <value><int>{self.rg_id}</int></value>
            </param>
        </params>
</methodCall>
```
8. change **rg_width = float(xml_response[0][0])** to **rg_busy = bool(xml_response[0][0])**
9. call the function with your robot_ip and tool_id (usually 0)

**Comment by kimanton** [comment]
@ViHin13 Thank you for this explanation, I think now I know enough to implement corresponding methods

**Comment by RyanPaulMcKenna** [comment]
Thanks for helping @kimanton  :)
